### ISSUE TITLE
Question about performing PCA 

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tensorpack#67]
Hey @cyrillustan! I was going to use your package for decomposition, and I realized that there is no scaling here.. Does your code assume that the tensor being inputted here is already normalized?

https://github.com/meyer-lab/tensorpack/blob/0a3a8e5a90666abe86c162285e07fa59c848249b/tensorpack/decomposition.py#L46C40-L46C40

Thanks,
Farnaz

**Comment by cyrillustan** [comment]
Hey Farnaz, are you talking about CP or PCA? 
For CP, it is normalized here https://github.com/meyer-lab/tensorpack/blob/0a3a8e5a90666abe86c162285e07fa59c848249b/tensorpack/cmtf.py#L117
For PCA, the scaling is included in the $\Sigma$ matrix (or `diag(S)` in the code) of SVD, so eventually the score matrix bears the weights.

**Comment by Farnazmdi** [comment]
Hey Cyrillus,
Thanks for your response. I was asking about the PCA. I didn't see the normalization in the `perform_PCA()`. So does it mean that we don't have to normalize the input data for `perform_PCA() and `tensorly's `svd_interface()` takes care of the normalization?

**Comment by cyrillustan** [comment]
Yes, for PCA, SVD deals with the scaling, so you don't have to normalize the data.
